# Enabling or disabling ComfyWhitelist. (true / false)
enabled: false

# Enabling or disabling clear command. (true / false)
# HIGH RISK COMMAND - DATA FROM THE WHITELIST WILL NOT BE RETURNED!!!
# enable this command ONLY if you really need it and trust your administrators
clear-command: false
